### ISSUE TITLE
local.css issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/herman-melville_moby-dick#5]
- Instead of using `class="roman"` we can do: `[epub|type~="chapter"] ol` and drop the class entirely
- Likewise we can drop `.translations` and instead target `[epub|type~="preamble"] table`. Classes should really only be used in cases where a certain class is found more than once in the work (i.e. it really is a "class" of elements and not "a way of targeting a single element"), or if it's totally impossible to unambiguously target an element otherwise.
- `tattoo p > span` is targeted in line 93 and 101 along with verse but does not seem to need verse styling. Also we can drop line 76 because p first-children already have text-indent 0.

**Comment by robinwhittleton** [comment]
Good catches! Fixed in https://github.com/robinwhittleton/herman-melville_moby-dick/commit/0c299a1347946d57db1dbc88de53a3a380e8cc1b, https://github.com/robinwhittleton/herman-melville_moby-dick/commit/d694de518b5d8e045e125cb0e07fe2f915fceb03 and https://github.com/robinwhittleton/herman-melville_moby-dick/commit/af95e21530a47895d9f71a3fc7136ffa0f266ed9.
